# Generated by Django 5.0.9 on 2024-11-23 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_file_alter_file_file_alter_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='file',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to='images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
            preserve_default=False,
        ),
    ]
